name: Release latest Docker Images

on:
  workflow_dispatch

  schedule:
    - cron: '0 0 1 1/3 *'
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3
    - name: Update Dockerfile
      run: make release
    - name: Store new version
      run: echo "FOOBAR_TEST=something" | tee -a $GITHUB_ENV
    # - name: Git Auto Commit
    #   uses: stefanzweifel/git-auto-commit-action@v4.16.0
    #   with:
    #     commit_message: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo ${{ env.FOOBAR_TEST }}
