name: Deploy New Docker Image Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1/3 *'

jobs:
  check-for-latest:
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.new-version.outputs.LATEST_VERSION }}
      hasNewVersion: ${{ steps.new-version.outputs.LATEST_VERSION != steps.current-version.outputs.CURRENT_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: Get new version number
      id: new-version
      run: echo "LATEST_VERSION=$(./get_latest_release_version.sh)" | tee -a $GITHUB_OUTPUT
    - name: Get current version
      id: current-version
      run: echo "CURRENT_VERSION=$(cat Dockerfile | sed -n -E 's/.*frp_version=([0-9.-]+)/\1/p')" | tee -a $GITHUB_OUTPUT
  update-and-deploy:
    needs: check-for-latest
    if: ${{ needs.check-for-latest.outputs.hasNewVersion }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Update Dockerfile
      run: |
        make release
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_ACCESS }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags:
          - sethicis/frp-docker:latest
          - sethicis/frp-docker:${{ needs.check-for-latest.outputs.newVersion }}