name: Deploy New Docker Image Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1/3 *'

env:
  REGISTRY: ghcr.io
  OWNER: sethicis
  IMAGE_NAME: frp-docker

jobs:
  check-for-latest:
    runs-on: ubuntu-latest
    outputs:
      newVersion: ${{ steps.new-version.outputs.LATEST_VERSION }}
      hasNewVersion: ${{ steps.new-version.outputs.LATEST_VERSION != steps.current-version.outputs.CURRENT_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - id: new-version
      run: echo "LATEST_VERSION=$(./get_latest_release_version.sh)" | tee -a $GITHUB_OUTPUT
    - id: current-version
      run: echo "CURRENT_VERSION=$(cat Dockerfile | sed -n -E 's/.*frp_version=([0-9.-]+)/\1/p')" | tee -a $GITHUB_OUTPUT
  update-and-deploy:
    needs: check-for-latest
    if: ${{ needs.check-for-latest.outputs.hasNewVersion == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Update Dockerfile
      run: |
        make release
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME}}:latest,${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.check-for-latest.outputs.newVersion }}
    - name: Create Pull Request
      if: ${{ success() }}
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Updated Dockerfile with v${{ needs.check-for-latest.outputs.newVersion }}
        branch: automerge/dockerfile-update-v${{ needs.check-for-latest.outputs.newVersion }}
        delete-branch: true
        title: "AUTO-UPDATE-DOCKERFILE: FRP v${{ needs.check-for-latest.outputs.newVersion }}"
        body: "Automated changes applied to update the Dockerfile with the latest FRP version.  New image tag(s) have been deployed to the registry."
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
